version: 1.0.{build}

platform: 
 - x86

clone_folder: c:\mgs

build_script:
 - call "comp_asm.bat"
 - ps: C:\mgs\check.ps1
 
install:
 - git submodule update --init --recursive
 - 7z x psyq.7z -oC:\
 - dir C:\psyq

test: off
